Algoritmo "semnome"
// comentario
// altor do programa: Laura

var
nota1, nota2, media: real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
// atribuir valores as variaveis

escreval("digite nota1 :")
//entrada de dados
leia (nota1)
escreval ("digite nota2 :")
leia (nota2)
//saida
media <- (nota1 + nota2) / 2
escreval ("sua media foi" , media)
se media >=7 entao
  escreval ("APROVADO")
senao
  escreval ("REPROVADO")
fimse

Fimalgoritmo