Algoritmo "exercicios"
//3. Faça um algoritmo que:
//a) Leia um número inteiro;
//b) Leia um segundo número inteiro;
//c) Efetue a adição dos dois valores;
//d) Apresente o valor calculado.
Var
num1, num2, resul: inteiro


Inicio
escreva ("Escreva o primeiro número: ")
leia (num1)
escreva ("Escreva o segundo número: ")
leia (num2)
resul <- num1+num2
escreval ("O resultado é:", resul)


Fimalgoritmo