Algoritmo "exercicios"
Var
area, raio, p, resul: real

Inicio
//1.Faça um algoritmo para calcular a área de uma circunferência,
// considerando a
//fórmula ÁREA = p * RAIO². Utilize as variáveis AREA e RAIO,
// a constante p (pi =3,14159) e os operadores aritméticos de multiplicação.

escreva ("Escreva o raio da circunferencia: ")
leia (raio)
p <- 3,14
area <-(raio*raio)*p
resul <- (p * raio)
escreval ("A área da circinferencia é: ", resul)






Fimalgoritmo