Algoritmo "exercicio"
//6. Faça um algoritmo que leia uma temperatura em Fahrenheit e a apresente
//convertida em graus Celsius. A fórmula de conversão é C = (F – 32) * ( 5 / 9), na
//qual F é a temperatura em Fahrenheit e C é a temperatura em Celcius.

Var
celsius, fah: real



Inicio
escreva ("Digite a temperatura em Fahrenheit:")
leia (fah)
celsius <- (fah-32)*(5/9)
escreval ("A temperatura em Celsius é:", celsius)





Fimalgoritmo