Algoritmo "semnome"
// 7. Faça um algoritmo que calcule e apresente o valor do volume
//de uma lata de óleo, utilizando a fórmula
//VOLUME = 3,14159 * RAIO * RAIO * ALTURA.
Var
volume, raio, altura: real



Inicio
escreva ("Digite a altura da lata de óleo:")
leia (altura)
escreva ("Digite o raio dela:")
leia (raio)
volume <- 3,14*raio*raio*altura
escreval ("O volume da lata é:", volume)





Fimalgoritmo