Algoritmo "exercicios"

Var
area, base, altura: real

// 2. Faça um algoritmo que calcule a área de um triângulo,
 //considerando a fórmula (base*altura)/2
//Utilize as variáveis AREA, BASE e ALTURA
//e os operadores aritméticos de multiplicação e divisão


Inicio
escreva ("Digite a base: ")
leia (base)
escreva ("Digite a altura: ")
leia (altura)
area <- (base*altura)/2
escreval ("a área é:", area)


Fimalgoritmo